version: '3.8'

services:
  data-science:
    build: .
    container_name: data_science_container
    working_dir: /app
    volumes:
      - .:/app  # Monta el directorio actual en /app del contenedor
    ports:
      - "8889:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  spark-data:

